[package]
name = "redactor-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core Library that serves as the backbone for Rusty Redactor."

[dependencies]
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
lopdf = "0.38.0"
pdfium-render = "0.8.37"



[lib]
name = "redactor_core"
crate-type = ["rlib"]

[dev-dependencies]